[project]
name = "cpu-chatbot-tutorial"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cerebras-cloud-sdk>=1.56.1",
    "openai>=2.6.1",
    "python-dotenv>=1.2.1",
]
